### ISSUE TITLE
Missing Package x86_64

### ISSUE THREAD

**Issue by ghost** [cloudwego/iasm#1]
github.com/cloudwego/iasm/x86_64: module github.com/cloudwego/iasm@latest found (v0.1.0), but does not contain package github.com/cloudwego/iasm/x86_64

https://github.com/cloudwego/iasm/actions/runs/8525216623

All your tests fail. I cannot update our dependencies as your package is broken.

Fix ASAP please

**Comment by lryong** [comment]
encounter the same issue

**Comment by felix021** [comment]
Please use this version of iasm:

```bash
go get github.com/cloudwego/iasm@v0.0.9
```

Refer to https://github.com/cloudwego/kitex/issues/1319 for more details.

**Comment by ghost** [comment]
How is an existing issue in another repository a valid reason to close this? Your own tests in this repository are failing with this issue.

The issue should be reopened until this is fixed! Very poor way of handling this..

<img width="637" alt="image" src="https://github.com/cloudwego/iasm/assets/92363078/4fce983a-f66a-4f4b-8164-234432a9432a">


> Error: iasm.go:4:5: cannot find package "github.com/cloudwego/iasm/arch/x86_64" in any of:
	/opt/hostedtoolcache/go/1.2.2/x64/src/pkg/github.com/cloudwego/iasm/arch/x86_64
	
	
<img width="736" alt="image" src="https://github.com/cloudwego/iasm/assets/92363078/76b20439-9eb6-435f-b26a-01a0a803fe3a">

**Comment by GuangmingLuo** [comment]
Sorry for the bad experience. 
The reason is that github.com/cloudwego/iasm@v0.1.0 has break change, and now v0.1.0 tag has been removed.
You may solve the issue by `go get github.com/cloudwego/iasm@v0.0.9`
And `go get -u ` will use v0.0.9 as the latest tag now.
@fabszabo Let me know if it solves your problem.

**Comment by felix021** [comment]
Sorry for the inconvenience.

This project is ported from a personal repository and we didn't pay attention to the workflow which is using go1.2 (not supported) and ARM64 (also not supported).

The v0.0.9 is just the same as the original version and v0.1.0 introduced incompatible changes and was wrongly set as the latest release.

We've removed v0.1.0 to avoid further confusion and will fix the workflow soon after, and release a newer version.

Before that, you can fix it by:

```
go get github.com/cloudwego/iasm@v0.0.9
```

We've republished v0.0.9 as v0.1.1 to solve furthur cases like this.

**Comment by ghost** [comment]
Thank you for the replies and good explanation. Changing the version to 0.0.9 did indeed work (golang 1.21)
